### ISSUE TITLE
Append spectrum to the Frequency Bar OnMouseDown

### ISSUE THREAD

**Issue by galArus1** [BoshenGuan/SpectrumDemo#1]
Hey, 
First of all, great repo, thank you very much.
there is any way to append the the spectrum chart to the frequency  when the event OnMouseDown occur?
Right now when you click and drag the mouse only the frequency bar changed and the spectrum char stay still, what is incorrect.
if there is no way, there you can tell how Its the correct way to set the frequency bar static(unchangeable) and spread the entire frequency on the  frequency bar accordingly to the spectrum data.

**Comment by BoshenGuan** [comment]
> Hey,
> First of all, great repo, thank you very much.
> there is any way to append the the spectrum chart to the frequency when the event OnMouseDown occur?
> Right now when you click and drag the mouse only the frequency bar changed and the spectrum char stay still, what is incorrect.
> if there is no way, there you can tell how Its the correct way to set the frequency bar static(unchangeable) and spread the entire frequency on the frequency bar accordingly to the spectrum data.

Hello, is it a built-in feature in SDRSharp, or is it a porting mistake?

I guess your problem is:
You don't implement your own event handlers. They are something like these:

Spectrum_BandwidthChanged
Spectrum_CenterFrequencyChanged
Spectrum_FrequencyChanged

Those handlers are called when user interacts with the control, for example, dragging. You have to change frequency of your SDR hardware when the handler is called and acquire new data values on new frequency. Do I understand your problem correctly? Let me know if you have any concerns.

Bests,

**Comment by BoshenGuan** [comment]
> Hey,
> First of all, great repo, thank you very much.
> there is any way to append the the spectrum chart to the frequency when the event OnMouseDown occur?
> Right now when you click and drag the mouse only the frequency bar changed and the spectrum char stay still, what is incorrect.
> if there is no way, there you can tell how Its the correct way to set the frequency bar static(unchangeable) and spread the entire frequency on the frequency bar accordingly to the spectrum data.

Moreover, you can try `e.Cancel = true;` in corresponding event handler (depends on your need) to cancel user's mouse events.

**Comment by galArus1** [comment]
Thank you very much, really helpful.
